spring:
  h2:
    console:
      enabled: true
      path: "/db"
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./database
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

